// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpk0f-HsDa_gMD1MQf285EgqGl99PyII',
    appId: '1:549685162106:web:df73151177766024274bc3',
    messagingSenderId: '549685162106',
    projectId: 'connectcall-ffb3c',
    authDomain: 'connectcall-ffb3c.firebaseapp.com',
    storageBucket: 'connectcall-ffb3c.firebasestorage.app',
    measurementId: 'G-2ECRPBYLWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5gQk5nLphkqptlWUnCrYkIPb99TWhbM',
    appId: '1:549685162106:android:bcc18eea4fbdb4f9274bc3',
    messagingSenderId: '549685162106',
    projectId: 'connectcall-ffb3c',
    storageBucket: 'connectcall-ffb3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7gr9SI4ZYyOchMCPmqLnNoYPm4hdlBQ',
    appId: '1:549685162106:ios:6dbcd42074ff1a75274bc3',
    messagingSenderId: '549685162106',
    projectId: 'connectcall-ffb3c',
    storageBucket: 'connectcall-ffb3c.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7gr9SI4ZYyOchMCPmqLnNoYPm4hdlBQ',
    appId: '1:549685162106:ios:6dbcd42074ff1a75274bc3',
    messagingSenderId: '549685162106',
    projectId: 'connectcall-ffb3c',
    storageBucket: 'connectcall-ffb3c.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpk0f-HsDa_gMD1MQf285EgqGl99PyII',
    appId: '1:549685162106:web:357ec64d1f704b7e274bc3',
    messagingSenderId: '549685162106',
    projectId: 'connectcall-ffb3c',
    authDomain: 'connectcall-ffb3c.firebaseapp.com',
    storageBucket: 'connectcall-ffb3c.firebasestorage.app',
    measurementId: 'G-5MFPKWP6JT',
  );
}
